---

# redis is available on port 6379 by default
- name: install redis in-memory database
  apt:
    pkg: redis-server

- name: declare an init system to manage redis as a service
  replace:
    path: /etc/redis/redis.conf
    regexp: '^supervised no*'
    replace: 'supervised systemd'
  notify: restart redis

- name: create directory to store redis override.conf
  file:
    path: /etc/systemd/system/redis-server.service.d
    state: directory
    owner: root
    group: root

- name: create override.conf to fix systemd start file for redis
  copy:
    dest: /etc/systemd/system/redis-server.service.d/override.conf
    content: |
      [Service]
      Type=notify
  notify: systemctl daemon-reload

- name: ensure redis is enabled and restarted
  service:
    name: redis
    enabled: yes

- name: set redis listen address
  replace:
    path: /etc/redis/redis.conf
    regexp: '^bind .*$'
    replace: "bind {{ redis_listen_address }}"
  notify: restart redis

- name: set redis listen port
  replace:
    path: /etc/redis/redis.conf
    regexp: '^port .*$'
    replace: "port {{ redis_listen_port }}"
  notify: restart redis
