---
- name: Create DNS records
  uri:
    url: https://dns.api.gandi.net/api/v5/domains/{{ parent_domain }}/records/{{ app_name }}
    method: PUT
    body_format: json
    headers:
      X-Api-Key: "{{ production_api_key }}"
    body:
      items:
        - rrset_type: A
          rrset_ttl: 3600
          rrset_values:
            - "{{ server.hcloud_server.ipv4_address }}"
        - rrset_type: AAAA
          rrset_ttl: 3600
          rrset_values:
            - "{{ server.hcloud_server.ipv6.split('/')[0] }}"
    status_code: 201
  become_user: True
